version: "3.8"

services:
  fin-webhooks:
    build: .
    container_name: fin-webhooks
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BELVO_SECRET_ID=${BELVO_SECRET_ID}
      - BELVO_SECRET_PASSWORD=${BELVO_SECRET_PASSWORD}
      - BELVO_API_URL=${BELVO_API_URL:-https://sandbox.belvo.com/api}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
