name: "Apply terraform"

on:
  workflow_call:
    inputs:
      aws-assume-role-arn:
        required: true
        type: string
      aws-region:
        type: string
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: "terraform-${{ github.sha }}"
          aws-region: ${{ inputs.aws-region }}

      - name: Initialize Terraform
        run: cd fin/infra && terraform init

      - name: Terraform validate
        run: cd fin/infra && terraform validate

      - name: Terraform plan
        id: terraform-plan
        run: cd fin/infra && terraform plan -out=${{ github.sha }}.out

      - name: Terraform apply
        run: cd fin/infra && terraform apply ${{ github.sha }}.out
